---
title:  "Execept Case"
excerpt: "파이썬의 예외 처리"
categories:
  - Py_Basic
last_modified_at: 2021-12-05

toc: true
toc_label: "Table Of Contents"
toc_icon: "cog"
toc_sticky: true

use_math: true
---

 파이썬의 예외 처리 방법에 대해서 작게나마 알아봅시다.
{: .notice--warning}

# [Python Function Object](#link){: .btn .btn--primary}{: .align-center}

> ## 에러란?

- 예외(exception)란 코드를 실행하는 중에 발생한 에러를 뜻합니다.
- 다음과 같이 10을 어떤 값으로 나누는 함수 ten_div가 있을 때 인수에 따라 정상으로 동작하기도 하고 에러가 나기도 합니다.

```python
>>> def ten_div(x):
...     return 10 / x
...
```

- 위 함수는 0을 넣으면 에러가 발생할 것입니다.

```
>>> ten_div(0)
Traceback (most recent call last):
  File "<pyshell#121>", line 1, in <module>
    ten_div(0)
  File "<pyshell#119>", line 2, in ten_div
    return 10 / x
ZeroDivisionError: division by zero 
```

- 위처럼 0으로 나누면 값이 정의가 되지 않기 때문에 에러가 발생하고 맙니다.
  - ZeroDivisionError뿐만 아니라 지금까지 만난 AttributeError, NameError, TypeError 등 다양한 에러들도 모두 예외입니다.
- 이번에는 예외가 발생했을 때도 스크립트 실행을 중단하지 않고 계속 실행하게 해주는 예외 처리 방법에 대해 알아보겠습니다.

> ## Try Except

- 예외 처리를 하려면 아래와 같이 try에 실행할 코드를 넣고 except에 예외가 발생했을 때 처리하는 코드를 넣습니다.

```python
try:
    실행할 코드
except:
    예외가 발생했을 때 처리하는 코드
```

- 이전에 우리의 ten_div 를 다음과 같이 정의할 수 있습니다.

```python
try:
    x = int(input('나눌 숫자를 입력하세요: '))
    y = 10 / x
    print(y)
except:    # 예외가 발생했을 때 실행됨
    print('예외가 발생했습니다.')
```

- 위에 대해서 x=0 을 넣으면 아래와 같은 출력이 나오게 됩니다.

```
나눌 숫자를 입력하세요: 0 (입력)
예외가 발생했습니다.
```

> 실행 방식

![jpg](/assets/images/Program/38_1.jpg)

- try의 코드가 에러 없이 잘 실행 되면 except의 코드는 실행되지 않고 그냥 넘어감
- try의 코드에서 에러가 발생했을 때만 except의 코드가 실행됨

> 특정 예외만 처리하기

- 이번에는 except에 예외 이름을 지정해서 특정 예외가 발생했을 때만 처리 코드를 실행하도록 만들어보겠습니다.

```python
try:
    실행할 코드
except 예외이름:
    예외가 발생했을 때 처리하는 코드
```

- 다음과 같은 코드를 작성해 보겠습니다.

```python
y = [10, 20, 30]
 
try:
    index, x = map(int, input('인덱스와 나눌 숫자를 입력하세요: ').split())
    print(y[index] / x)
except ZeroDivisionError:    # 숫자를 0으로 나눠서 에러가 발생했을 때 실행됨
    print('숫자를 0으로 나눌 수 없습니다.')
except IndexError:           # 범위를 벗어난 인덱스에 접근하여 에러가 발생했을 때 실행됨
    print('잘못된 인덱스입니다.')
```

- 위 코드를 실행한 뒤, 에러를 발생시킨 뒤 엔터를 눌러봅시다.

```
인덱스와 나눌 숫자를 입력하세요: 2 0 (입력)
숫자를 0으로 나눌 수 없습니다. 
```

```
인덱스와 나눌 숫자를 입력하세요: 3 5 (입력)
잘못된 인덱스입니다.
```

- 위처럼 각각의 에러에 대해서 다른 처리를 할 수 있습니다.

> 에러 메세지 받아오기

- 특히 except에서 as 뒤에 변수를 지정하면 발생한 예외의 에러 메시지를 받아올 수 있습니다.

```
try:
    실행할 코드
except 예외 as 변수:
    예외가 발생했을 때 처리하는 코드
```

- 앞에서 만든 코드의 except에 as e를 넣습니다. 보통 예외( **e**xception)의 e를 따서 변수 이름을 e로 짓습니다.

```python
y = [10, 20, 30]
 
try:
    index, x = map(int, input('인덱스와 나눌 숫자를 입력하세요: ').split())
    print(y[index] / x)
except ZeroDivisionError as e:                    # as 뒤에 변수를 지정하면 에러를 받아옴
    print('숫자를 0으로 나눌 수 없습니다.', e)    # e에 저장된 에러 메시지 출력
except IndexError as e:
    print('잘못된 인덱스입니다.', e
```

```
인덱스와 나눌 숫자를 입력하세요: 2 0 (입력)
숫자를 0으로 나눌 수 없습니다. division by zero
```

```
인덱스와 나눌 숫자를 입력하세요: 3 5 (입력)
잘못된 인덱스입니다. list index out of range
```

- 2 0, 3 5처럼 예외가 발생하는 숫자를 넣어보면 해당 예외에 해당하는 에러 메시지가 출력됩니다. 
- 단, 예외가 여러 개 발생하더라도 먼저 발생한 예외의 처리 코드만 실행됩니다(또는, 예외 중에서 높은 계층의 예외부터 처리됩니다. 기반 클래스 > 파생 클래스 순).

![jpg](/assets/images/Program/38_2.jpg)

> 모든 예외의 에러 메시지 출력하기

- 참고로 모든 예외의 에러 메시지를 출력하고 싶다면 다음과 같이 except에 Exception을 지정하고 as 뒤에 변수를 넣으면 됩니다.

```
except Exception as e:    # 모든 예외의 에러 메시지를 출력할 때는 Exception을 사용
    print('예외가 발생했습니다.', e)
```

> ## Try Except else

- 이번에는 예외가 발생하지 않았을 때 코드를 실행하는 else를 사용해보겠습니다. 다음과 같이 else는 except 바로 다음에 와야 하며 except를 생략할 수 없습니다.

```python
try:
    실행할 코드
except:
    예외가 발생했을 때 처리하는 코드
else:
    예외가 발생하지 않았을 때 실행할 코드
```

- 그럼 10을 입력된 숫자로 나누고 예외가 발생하지 않으면 계산 결과를 출력해보겠습니다.

```python
try:
    x = int(input('나눌 숫자를 입력하세요: '))
    y = 10 / x
except ZeroDivisionError:    # 숫자를 0으로 나눠서 에러가 발생했을 때 실행됨
    print('숫자를 0으로 나눌 수 없습니다.')
else:                        # try의 코드에서 예외가 발생하지 않았을 때 실행됨
    print(y)
```



---

**reference**

- <https://dojang.io/mod/page/view.php?id=2399>





